n_timesteps: 1000000
learning_rate: 0.0003
n_steps: 2048
batch_size: 256
n_epochs: 10
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
normalize_advantage: False
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
use_sde: False
sde_sample_freq: -1
target_kl: 0.1
stats_window_size: 100
verbose: 1
seed: 42
device: "cuda"
tensorboard_log: "logs/tensorboard"

policy_kwargs:
  normalize_images: False