seed: 42
n_timesteps: 1e6
learning_rate: 0.001
batch_size: 256
gamma: 0.99
tau: 0.005
train_freq: 1
gradient_steps: 1
optimize_memory_usage: False 
device: "cuda"
tensorboard_log: "logs/tensorboard"

policy_kwargs:
  normalize_images: False