seed: 42
n_timesteps: 1000000
learning_rate: 0.001
batch_size: 256
gamma: 0.99
tau: 0.005
train_freq: 1
gradient_steps: 1
optimize_memory_usage: False 
target_policy_noise: 0.2
target_noise_clip: 0.5
device: "cuda"
tensorboard_log: "logs/tensorboard"

policy_kwargs:
  normalize_images: False